scratchBucket:
  # Enable a 'scratch' bucket per-hub, with read-write permissions for all
  # users. This will set a `SCRATCH_BUCKET` env variable (and a PANGEO_SCRATCH variable
  # too, for backwards compatibility). Users can share data with each other using
  # this bucket.
  enabled: true

basehub:
  # Copied from https://github.com/dask/helm-chart/blob/master/daskhub/values.yaml
  # FIXME: Properly use the upstream chart.
  jupyterhub:
    prePuller:
      hook:
        enabled: false
    singleuser:
      # Almost everyone using dask by default wants JupyterLab
      defaultUrl: /lab
      extraLabels:
         hub.jupyter.org/network-access-proxy-http: "true"

      networkPolicy:
        egress:
          # Needed to talk to metadata server.
          # see https://github.com/2i2c-org/pilot-hubs/issues/280
          - to:
              - ipBlock:
                  cidr: 127.0.0.1/32
            ports:
              - port: 988
                protocol: TCP
          # Needed for talking to the proxy pod
          - ports:
              - port: 8000
                protocol: TCP
          - ports:
              - port: 80
                protocol: TCP
          - ports:
              - port: 443
                protocol: TCP
          # Enable outgoing ssh by default on these hubs
          - ports:
              - port: 22
                protocol: TCP
      cloudMetadata:
        # Don't block access to AWS cloud metadata
        # If we don't, our users can't access S3 buckets / other AWS services
        # without an explicit identity
        # FIXME: Provide an explicit identity for users instead
        blockWithIptables: false
      serviceAccountName: user-sa
      extraEnv:
        # About DASK_ prefixed variables we set:
        #
        # 1. k8s native variable expansion is applied with $(MY_ENV) syntax. The
        #    order variables are defined matters though and we are under the
        #    mercy of how KubeSpawner renders our passed dictionaries.
        #
        # 2. Dask loads local YAML config.
        #
        # 3. Dask loads environment variables prefixed DASK_.
        #    - DASK_ is stripped
        #    - Capitalization is ignored
        #    - Double underscore means a nested configuration
        #    - `ast.literal_eval` is used to parse values
        #
        # 4. dask-gateway and dask-distributed looks at its config and expands
        #    expressions in {} again, sometimes only with the environment
        #    variables as context but sometimes also with additional variables.
        #
        # References:
        # - K8s expansion:     https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/
        # - KubeSpawner issue: https://github.com/jupyterhub/kubespawner/issues/491
        # - Dask config:       https://docs.dask.org/en/latest/configuration.html
        # - Exploration issue: https://github.com/2i2c-org/pilot-hubs/issues/442
        #
        DASK_GATEWAY__CLUSTER__OPTIONS__IMAGE: '{JUPYTER_IMAGE_SPEC}'
        # Try make this show up before SCRATCH_BUCKET but after JUPYTERHUB_USER
        # by naming its entry.
        SCRATCH_A:
          name: DASK_GATEWAY__CLUSTER__OPTIONS__ENVIRONMENT
          value: '{"SCRATCH_BUCKET": "$(SCRATCH_BUCKET)"}'
        DASK_DISTRIBUTED__DASHBOARD_LINK: '/user/{JUPYTERHUB_USER}/proxy/{port}/status'
        DASK_LABEXTENSION__FACTORY__MODULE: 'dask_gateway'
        DASK_LABEXTENSION__FACTORY__CLASS: 'GatewayCluster'

    hub:
      networkPolicy:
        enabled: false
      extraConfig:
        daskhub-01-add-dask-gateway-values: |
          # 1. Sets `DASK_GATEWAY__PROXY_ADDRESS` in the singleuser environment.
          # 2. Adds the URL for the Dask Gateway JupyterHub service.
          import os
          # These are set by jupyterhub.
          release_name = os.environ["HELM_RELEASE_NAME"]
          release_namespace = os.environ["POD_NAMESPACE"]
          if "PROXY_HTTP_SERVICE_HOST" in os.environ:
              # https is enabled, we want to use the internal http service.
              gateway_address = "http://{}:{}/services/dask-gateway/".format(
                  os.environ["PROXY_HTTP_SERVICE_HOST"],
                  os.environ["PROXY_HTTP_SERVICE_PORT"],
              )
              print("Setting DASK_GATEWAY__ADDRESS {} from HTTP service".format(gateway_address))
          else:
              gateway_address = "http://proxy-public/services/dask-gateway"
              print("Setting DASK_GATEWAY__ADDRESS {}".format(gateway_address))
          # Internal address to connect to the Dask Gateway.
          c.KubeSpawner.environment.setdefault("DASK_GATEWAY__ADDRESS", gateway_address)
          # Internal address for the Dask Gateway proxy.
          c.KubeSpawner.environment.setdefault("DASK_GATEWAY__PROXY_ADDRESS", "gateway://traefik-{}-dask-gateway.{}:80".format(release_name, release_namespace))
          # Relative address for the dashboard link.
          c.KubeSpawner.environment.setdefault("DASK_GATEWAY__PUBLIC_ADDRESS", "/services/dask-gateway/")
          # Use JupyterHub to authenticate with Dask Gateway.
          c.KubeSpawner.environment.setdefault("DASK_GATEWAY__AUTH__TYPE", "jupyterhub")
          # Adds Dask Gateway as a JupyterHub service to make the gateway available at
          # {HUB_URL}/services/dask-gateway
          service_url = "http://traefik-{}-dask-gateway.{}".format(release_name, release_namespace)
          for service in c.JupyterHub.services:
              if service["name"] == "dask-gateway":
                  if not service.get("url", None):
                      print("Adding dask-gateway service URL")
                      service.setdefault("url", service_url)
                  break
          else:
              print("dask-gateway service not found. Did you set jupyterhub.hub.services.dask-gateway.apiToken?")

dask-gateway:
  enabled: true  # Enabling dask-gateway will install Dask Gateway as a dependency.
  # Futher Dask Gateway configuration goes here
  # See https://github.com/dask/dask-gateway/blob/master/resources/helm/dask-gateway/values.yaml
  controller:
    nodeSelector:
      k8s.dask.org/node-purpose: core
  gateway:
    nodeSelector:
      k8s.dask.org/node-purpose: core
    backend:
      scheduler:
        extraPodConfig:
          serviceAccountName: user-sa
          tolerations:
            # Let's put schedulers on notebook nodes, since they aren't ephemeral
            # dask can recover from dead workers, but not dead schedulers
            - key: "hub.jupyter.org/dedicated"
              operator: "Equal"
              value: "user"
              effect: "NoSchedule"
            - key: "hub.jupyter.org_dedicated"
              operator: "Equal"
              value: "user"
              effect: "NoSchedule"
          nodeSelector:
              k8s.dask.org/node-purpose: scheduler
        cores:
          request: 0.01
          limit: 1
        memory:
          request: 128M
          limit: 1G
      worker:
        extraContainerConfig:
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
        extraPodConfig:
          serviceAccountName: user-sa
          securityContext:
            fsGroup: 1000
          tolerations:
            - key: "k8s.dask.org/dedicated"
              operator: "Equal"
              value: "worker"
              effect: "NoSchedule"
            - key: "k8s.dask.org_dedicated"
              operator: "Equal"
              value: "worker"
              effect: "NoSchedule"
          nodeSelector:
            # Dask workers get their own pre-emptible pool
            k8s.dask.org/node-purpose: worker

    # TODO: figure out a replacement for userLimits.
    extraConfig:
      # This configuration represents options that can be presented to users
      # that want to create a Dask cluster using dask-gateway. For more
      # details, see https://gateway.dask.org/cluster-options.html
      #
      # The goal is to provide a simple configuration that allow the user some
      # flexibility while also fitting well well on AWS nodes that are all
      # having 1:4 ratio between CPU and GB of memory. By providing the
      # username label, we help administrators to track user pods.
      option_handler: |
        from dask_gateway_server.options import Options, Select, String, Mapping
        def cluster_options(user):
            def option_handler(options):
                if ":" not in options.image:
                    raise ValueError("When specifying an image you must also provide a tag")

                # FIXME: No user labels or annotations, until
                #        https://github.com/pangeo-data/pangeo-cloud-federation/issues/879
                #        is fixed. Its purpose is for housekeeping only though.
                extra_annotations = {
                    # "hub.jupyter.org/username": user.name,
                    "prometheus.io/scrape": "true",
                    "prometheus.io/port": "8787",
                }
                extra_labels = {
                    # "hub.jupyter.org/username": user.name,
                }
                chosen_worker_cpu = int(options.worker_specification.split("CPU")[0])
                chosen_worker_memory = 4 * chosen_worker_cpu

                # We multiply the requests by a fraction to ensure that the
                # worker fit well within a node that need some resources
                # reserved for system pods.
                return {
                    # A default image is suggested via DASK_GATEWAY__CLUSTER__OPTIONS__IMAGE env variable
                    "image": options.image,
                    "scheduler_extra_pod_labels": extra_labels,
                    "scheduler_extra_pod_annotations": extra_annotations,
                    "worker_extra_pod_labels": extra_labels,
                    "worker_extra_pod_annotations": extra_annotations,
                    "worker_cores": 0.85 * chosen_worker_cpu,
                    "worker_cores_limit": chosen_worker_cpu,
                    "worker_memory": "%fG" % (0.85 * chosen_worker_memory),
                    "worker_memory_limit": "%fG" % chosen_worker_memory,
                    "environment": options.environment,
                }
            return Options(
                Select(
                    "worker_specification",
                    [
                        "1CPU, 4GB",
                        "2CPU, 8GB",
                        "4CPU, 16GB",
                        "8CPU, 32GB",
                        "16CPU, 64GB",
                        "32CPU, 128GB",
                        "64CPU, 256GB",
                    ],
                    default="1CPU, 4GB",
                    label="Worker specification",
                ),
                # The default image is set via DASK_GATEWAY__CLUSTER__OPTIONS__IMAGE env variable
                String("image", label="Image"),
                Mapping("environment", {}, label="Environment variables"),
                handler=option_handler,
            )
        c.Backend.cluster_options = cluster_options
      idle: |
        # timeout after 30 minutes of inactivity
        c.KubeClusterConfig.idle_timeout = 1800
      limits: |
        # per Dask cluster limits.
        c.ClusterConfig.cluster_max_cores = 256
        c.ClusterConfig.cluster_max_memory = "1028G"
    prefix: "/services/dask-gateway"  # Users connect to the Gateway through the JupyterHub service.
    auth:
      type: jupyterhub  # Use JupyterHub to authenticate with Dask Gateway
  traefik:
    nodeSelector:
      k8s.dask.org/node-purpose: core
    service:
      type: ClusterIP  # Access Dask Gateway through JupyterHub. To access the Gateway from outside JupyterHub, this must be changed to a `LoadBalancer`.
